name: Playwright Tests
on:
  push:
    branches: [ main, master, env-credentials ]
  pull_request:
    branches: [ main, master, env-credentials ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci --force
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps --force
    - name: Run Playwright tests
      run: npm run dev-run
      env:
          TRELLO_EMAIL: ${{ secrets.TRELLO_EMAIL }}
          TRELLO_PASSWORD: ${{ secrets.TRELLO_PASSWORD }}
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: test-results/
        retention-days: 30